# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import ground_control_pb2 as ground__control__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ground_control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GroundControlStub(object):
    """The ground control service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMap = channel.unary_unary(
                '/GroundControl/GetMap',
                request_serializer=ground__control__pb2.MapRequest.SerializeToString,
                response_deserializer=ground__control__pb2.MapResponse.FromString,
                _registered_method=True)
        self.GetCommands = channel.unary_unary(
                '/GroundControl/GetCommands',
                request_serializer=ground__control__pb2.CommandRequest.SerializeToString,
                response_deserializer=ground__control__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.GetMineSerial = channel.unary_unary(
                '/GroundControl/GetMineSerial',
                request_serializer=ground__control__pb2.SerialNumRequest.SerializeToString,
                response_deserializer=ground__control__pb2.SerialNumResponse.FromString,
                _registered_method=True)


class GroundControlServicer(object):
    """The ground control service definition
    """

    def GetMap(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCommands(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMineSerial(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GroundControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMap': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMap,
                    request_deserializer=ground__control__pb2.MapRequest.FromString,
                    response_serializer=ground__control__pb2.MapResponse.SerializeToString,
            ),
            'GetCommands': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCommands,
                    request_deserializer=ground__control__pb2.CommandRequest.FromString,
                    response_serializer=ground__control__pb2.CommandResponse.SerializeToString,
            ),
            'GetMineSerial': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMineSerial,
                    request_deserializer=ground__control__pb2.SerialNumRequest.FromString,
                    response_serializer=ground__control__pb2.SerialNumResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GroundControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('GroundControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GroundControl(object):
    """The ground control service definition
    """

    @staticmethod
    def GetMap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/GroundControl/GetMap',
            ground__control__pb2.MapRequest.SerializeToString,
            ground__control__pb2.MapResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCommands(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/GroundControl/GetCommands',
            ground__control__pb2.CommandRequest.SerializeToString,
            ground__control__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMineSerial(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/GroundControl/GetMineSerial',
            ground__control__pb2.SerialNumRequest.SerializeToString,
            ground__control__pb2.SerialNumResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
