# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ground_control.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'ground_control.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14ground_control.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x0c\n\nMapRequest\"\x17\n\x06MapRow\x12\r\n\x05\x63\x65lls\x18\x01 \x03(\t\"F\n\x0bMapResponse\x12\x15\n\x04grid\x18\x01 \x03(\x0b\x32\x07.MapRow\x12\x0f\n\x07numRows\x18\x02 \x01(\x05\x12\x0f\n\x07numCols\x18\x03 \x01(\x05\"\"\n\x0e\x43ommandRequest\x12\x10\n\x08rover_id\x18\x01 \x01(\x05\"#\n\x0f\x43ommandResponse\x12\x10\n\x08\x63ommands\x18\x01 \x01(\t\"0\n\x10SerialNumRequest\x12\r\n\x05x_pos\x18\x01 \x01(\x05\x12\r\n\x05y_pos\x18\x02 \x01(\x05\"&\n\x11SerialNumResponse\x12\x11\n\tserialNum\x18\x01 \x01(\t\"A\n\x0f\x45xecutionStatus\x12\x10\n\x08rover_id\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0b\n\x03msg\x18\x03 \x01(\t\"(\n\x07MinePin\x12\x10\n\x08rover_id\x18\x01 \x01(\x05\x12\x0b\n\x03pin\x18\x02 \x01(\t2\x93\x02\n\rGroundControl\x12%\n\x06GetMap\x12\x0b.MapRequest\x1a\x0c.MapResponse\"\x00\x12\x32\n\x0bGetCommands\x12\x0f.CommandRequest\x1a\x10.CommandResponse\"\x00\x12\x38\n\rGetMineSerial\x12\x11.SerialNumRequest\x1a\x12.SerialNumResponse\"\x00\x12:\n\x0cReportStatus\x12\x10.ExecutionStatus\x1a\x16.google.protobuf.Empty\"\x00\x12\x31\n\x0bShareMinPin\x12\x08.MinePin\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ground_control_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MAPREQUEST']._serialized_start=53
  _globals['_MAPREQUEST']._serialized_end=65
  _globals['_MAPROW']._serialized_start=67
  _globals['_MAPROW']._serialized_end=90
  _globals['_MAPRESPONSE']._serialized_start=92
  _globals['_MAPRESPONSE']._serialized_end=162
  _globals['_COMMANDREQUEST']._serialized_start=164
  _globals['_COMMANDREQUEST']._serialized_end=198
  _globals['_COMMANDRESPONSE']._serialized_start=200
  _globals['_COMMANDRESPONSE']._serialized_end=235
  _globals['_SERIALNUMREQUEST']._serialized_start=237
  _globals['_SERIALNUMREQUEST']._serialized_end=285
  _globals['_SERIALNUMRESPONSE']._serialized_start=287
  _globals['_SERIALNUMRESPONSE']._serialized_end=325
  _globals['_EXECUTIONSTATUS']._serialized_start=327
  _globals['_EXECUTIONSTATUS']._serialized_end=392
  _globals['_MINEPIN']._serialized_start=394
  _globals['_MINEPIN']._serialized_end=434
  _globals['_GROUNDCONTROL']._serialized_start=437
  _globals['_GROUNDCONTROL']._serialized_end=712
# @@protoc_insertion_point(module_scope)
